// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bitbucket-repository-management-service/dm/proto-files/service/repository-service.proto

package service

import (
	domain "bitbucket-repository-management-service/dm/grpc/domain"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddRepositoryResponse struct {
	AddedRepository      *domain.Repository `protobuf:"bytes,1,opt,name=addedRepository,proto3" json:"addedRepository,omitempty"`
	Error                *Error             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AddRepositoryResponse) Reset()         { *m = AddRepositoryResponse{} }
func (m *AddRepositoryResponse) String() string { return proto.CompactTextString(m) }
func (*AddRepositoryResponse) ProtoMessage()    {}
func (*AddRepositoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b23d9f94ebddf09, []int{0}
}

func (m *AddRepositoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRepositoryResponse.Unmarshal(m, b)
}
func (m *AddRepositoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRepositoryResponse.Marshal(b, m, deterministic)
}
func (m *AddRepositoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRepositoryResponse.Merge(m, src)
}
func (m *AddRepositoryResponse) XXX_Size() int {
	return xxx_messageInfo_AddRepositoryResponse.Size(m)
}
func (m *AddRepositoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRepositoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRepositoryResponse proto.InternalMessageInfo

func (m *AddRepositoryResponse) GetAddedRepository() *domain.Repository {
	if m != nil {
		return m.AddedRepository
	}
	return nil
}

func (m *AddRepositoryResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b23d9f94ebddf09, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AddRepositoryResponse)(nil), "service.AddRepositoryResponse")
	proto.RegisterType((*Error)(nil), "service.Error")
}

func init() {
	proto.RegisterFile("bitbucket-repository-management-service/dm/proto-files/service/repository-service.proto", fileDescriptor_1b23d9f94ebddf09)
}

var fileDescriptor_1b23d9f94ebddf09 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0xa5, 0x6a, 0x2d, 0x1d, 0x41, 0x71, 0x40, 0x08, 0x3d, 0x88, 0x14, 0x0f, 0x5e, 0x92, 0x40,
	0x45, 0xa4, 0xe0, 0x45, 0xc1, 0x6b, 0x0f, 0xeb, 0x41, 0xf0, 0xb6, 0xc9, 0x8c, 0x61, 0xd1, 0xcd,
	0x86, 0xd9, 0x55, 0x10, 0x7f, 0x5e, 0xdc, 0x34, 0x75, 0x91, 0x5e, 0xf4, 0xb6, 0xef, 0xcd, 0xbc,
	0xf7, 0x76, 0x66, 0xe0, 0xb1, 0x32, 0xa1, 0x7a, 0xab, 0x5f, 0x38, 0xe4, 0xc2, 0x9d, 0xf3, 0x26,
	0x38, 0xf9, 0xc8, 0xad, 0x6e, 0x75, 0xc3, 0x96, 0xdb, 0x90, 0x7b, 0x96, 0x77, 0x53, 0x73, 0x49,
	0xb6, 0xec, 0xc4, 0x05, 0x97, 0x3f, 0x9b, 0x57, 0xf6, 0xe5, 0x40, 0x27, 0xa2, 0x35, 0x55, 0xc4,
	0x36, 0x9c, 0xac, 0xe1, 0x6c, 0xf5, 0xcf, 0x04, 0x72, 0x56, 0x9b, 0x36, 0x09, 0xe8, 0x8d, 0xe7,
	0x9f, 0x70, 0x72, 0x4b, 0xa4, 0x36, 0xb4, 0x62, 0xdf, 0xb9, 0xd6, 0x33, 0xde, 0xc0, 0x91, 0x26,
	0xe2, 0xa4, 0x94, 0x8d, 0xce, 0x46, 0x17, 0x07, 0x0b, 0x2c, 0x7a, 0xaf, 0x22, 0x11, 0xfd, 0x6e,
	0xc5, 0x73, 0x18, 0xb3, 0x88, 0x93, 0x6c, 0x27, 0x6a, 0x0e, 0x8b, 0x61, 0x9c, 0xfb, 0x6f, 0x56,
	0xf5, 0xc5, 0xf9, 0x15, 0x8c, 0x23, 0x46, 0x84, 0xbd, 0xda, 0x11, 0xc7, 0x84, 0xa9, 0x8a, 0x6f,
	0xcc, 0x60, 0x62, 0xd9, 0x7b, 0xdd, 0x70, 0x34, 0x99, 0xaa, 0x01, 0x2e, 0x56, 0x70, 0xfc, 0x13,
	0xf5, 0xd0, 0x1b, 0xe3, 0x12, 0x76, 0x35, 0x11, 0x6e, 0xf9, 0xdd, 0xec, 0x74, 0x93, 0xbe, 0x75,
	0xd4, 0xbb, 0xe5, 0xd3, 0xf5, 0x1f, 0xb6, 0xda, 0x48, 0x57, 0x0f, 0x07, 0xab, 0xf6, 0xe3, 0x16,
	0x2f, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x82, 0x4c, 0xbb, 0xf9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RepositoryServiceClient is the client API for RepositoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RepositoryServiceClient interface {
	Add(ctx context.Context, in *domain.Repository, opts ...grpc.CallOption) (*AddRepositoryResponse, error)
}

type repositoryServiceClient struct {
	cc *grpc.ClientConn
}

func NewRepositoryServiceClient(cc *grpc.ClientConn) RepositoryServiceClient {
	return &repositoryServiceClient{cc}
}

func (c *repositoryServiceClient) Add(ctx context.Context, in *domain.Repository, opts ...grpc.CallOption) (*AddRepositoryResponse, error) {
	out := new(AddRepositoryResponse)
	err := c.cc.Invoke(ctx, "/service.RepositoryService/add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepositoryServiceServer is the server API for RepositoryService service.
type RepositoryServiceServer interface {
	Add(context.Context, *domain.Repository) (*AddRepositoryResponse, error)
}

// UnimplementedRepositoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRepositoryServiceServer struct {
}

func (*UnimplementedRepositoryServiceServer) Add(ctx context.Context, req *domain.Repository) (*AddRepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterRepositoryServiceServer(s *grpc.Server, srv RepositoryServiceServer) {
	s.RegisterService(&_RepositoryService_serviceDesc, srv)
}

func _RepositoryService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domain.Repository)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.RepositoryService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).Add(ctx, req.(*domain.Repository))
	}
	return interceptor(ctx, in, info, handler)
}

var _RepositoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.RepositoryService",
	HandlerType: (*RepositoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "add",
			Handler:    _RepositoryService_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bitbucket-repository-management-service/dm/proto-files/service/repository-service.proto",
}
