// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bitbucket-repository-management-service/dm/proto-files/service/todo-service.proto

package service

import (
	domain "bitbucket-repository-management-service/dm/grpc/domain"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("bitbucket-repository-management-service/dm/proto-files/service/todo-service.proto", fileDescriptor_afc5efc4cd32179e)
}

var fileDescriptor_afc5efc4cd32179e = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x6e, 0xd3, 0x4e,
	0x10, 0xc6, 0xe5, 0xb4, 0xff, 0x44, 0xff, 0x6d, 0x51, 0xcb, 0xd2, 0x16, 0x29, 0xe2, 0x60, 0xe5,
	0x18, 0x61, 0x6f, 0x1a, 0x22, 0x55, 0x0a, 0x17, 0x02, 0x11, 0x02, 0x21, 0x0e, 0x04, 0xb8, 0xf4,
	0xb6, 0xb1, 0x07, 0x67, 0xcb, 0x7a, 0xc7, 0xec, 0x8e, 0x5b, 0x10, 0xe2, 0x82, 0x84, 0xc4, 0x19,
	0x6e, 0x1c, 0xb8, 0xf3, 0x1a, 0xbc, 0x02, 0xaf, 0xc0, 0x83, 0x20, 0xaf, 0x6d, 0x29, 0x25, 0x1c,
	0xe0, 0x92, 0x68, 0xbe, 0xfd, 0xfc, 0xfb, 0x66, 0xec, 0x59, 0xf6, 0x64, 0xa9, 0x68, 0x59, 0x26,
	0x2f, 0x81, 0x22, 0x0b, 0x05, 0x3a, 0x45, 0x68, 0xdf, 0x44, 0xb9, 0x34, 0x32, 0x83, 0x1c, 0x0c,
	0x45, 0x0e, 0xec, 0xb9, 0x4a, 0x40, 0xa4, 0xb9, 0x28, 0x2c, 0x12, 0x46, 0x2f, 0x94, 0x06, 0x27,
	0x5a, 0x99, 0x30, 0xc5, 0xd6, 0x13, 0x7b, 0x03, 0xef, 0x35, 0x65, 0x9f, 0x55, 0x87, 0xb5, 0xd8,
	0xbf, 0x91, 0x21, 0x66, 0x1a, 0x84, 0x2c, 0x94, 0x90, 0xc6, 0x20, 0x49, 0x52, 0x68, 0x5c, 0x73,
	0x7a, 0xd3, 0xff, 0x25, 0x51, 0x06, 0x26, 0x72, 0x17, 0x32, 0xcb, 0xc0, 0x0a, 0x2c, 0xbc, 0x63,
	0xd3, 0x3d, 0xfe, 0xb6, 0xc5, 0x76, 0x9e, 0xe1, 0x1c, 0x9f, 0xd6, 0x39, 0xfc, 0x21, 0xeb, 0xde,
	0xb3, 0x20, 0x09, 0xf8, 0x61, 0x9c, 0x62, 0x2e, 0x95, 0x89, 0xeb, 0x7a, 0x01, 0xaf, 0x4a, 0x70,
	0xd4, 0x3f, 0xfa, 0x5d, 0x76, 0x05, 0x1a, 0x07, 0x83, 0xfd, 0xf7, 0x3f, 0x7e, 0x7e, 0xee, 0xb0,
	0xc1, 0x7f, 0x7e, 0x8c, 0x69, 0x30, 0xe4, 0x0f, 0xd8, 0xf6, 0x02, 0x64, 0xca, 0xaf, 0xb5, 0x4f,
	0x54, 0x55, 0x8b, 0x39, 0xb8, 0x2c, 0x36, 0x90, 0x43, 0x0f, 0xd9, 0x1b, 0x30, 0x0f, 0x11, 0x6f,
	0x55, 0xfa, 0xae, 0x22, 0x29, 0xd6, 0x7d, 0x5e, 0xa4, 0x97, 0x9a, 0xaa, 0xeb, 0x8d, 0xa6, 0x5a,
	0xb9, 0xe1, 0x8d, 0x3c, 0x6f, 0xd8, 0xdf, 0x6b, 0x78, 0x84, 0x73, 0x8c, 0x6b, 0xe8, 0xe9, 0xc1,
	0xf8, 0x0f, 0x2a, 0x7f, 0xc4, 0xba, 0x73, 0xd0, 0xb0, 0x1e, 0x55, 0xd7, 0x1b, 0x51, 0xad, 0xdc,
	0x44, 0x71, 0x1f, 0xb5, 0x3b, 0x5c, 0x6b, 0x9d, 0x3f, 0x66, 0xbd, 0x6a, 0xbc, 0x99, 0xd6, 0xfc,
	0x68, 0x7d, 0xde, 0x99, 0xd6, 0x2d, 0xee, 0xfa, 0x86, 0xde, 0xf0, 0xae, 0x7a, 0xde, 0x0e, 0xff,
	0xbf, 0xe6, 0x49, 0xad, 0xef, 0x7e, 0xef, 0x7c, 0x9a, 0x7d, 0xe8, 0xf0, 0xaf, 0x01, 0xdb, 0xad,
	0x3e, 0x59, 0xd8, 0xec, 0xc6, 0xe0, 0x63, 0xc0, 0x44, 0x86, 0x51, 0x66, 0x8b, 0x24, 0x5a, 0x11,
	0x15, 0x91, 0x05, 0x47, 0x51, 0xae, 0x12, 0x8b, 0x8d, 0x25, 0xa2, 0x92, 0xd0, 0x2a, 0xa9, 0xc3,
	0xc2, 0xe2, 0x19, 0x24, 0xc4, 0xef, 0x57, 0x46, 0x37, 0x15, 0x22, 0x53, 0xb4, 0x2a, 0x97, 0x71,
	0x82, 0xb9, 0x48, 0xa5, 0x85, 0x14, 0xce, 0x95, 0x3e, 0x3e, 0x11, 0x7f, 0xb9, 0xca, 0xfd, 0x2b,
	0x04, 0x8e, 0xee, 0x54, 0x3f, 0x15, 0x62, 0xbc, 0x75, 0x1c, 0x8f, 0x86, 0x41, 0x30, 0xde, 0x97,
	0x45, 0xa1, 0x55, 0xe2, 0x57, 0x4d, 0x9c, 0x39, 0x34, 0xd3, 0x0d, 0x65, 0x71, 0x9b, 0x6d, 0x4d,
	0x46, 0x13, 0x3e, 0x61, 0xc3, 0x05, 0x50, 0x69, 0x0d, 0xa4, 0xe1, 0xc5, 0x0a, 0x4c, 0x48, 0x2b,
	0x08, 0x2d, 0x38, 0x2c, 0x6d, 0x02, 0x61, 0x8a, 0xe0, 0x42, 0x83, 0x14, 0xc2, 0x6b, 0xe5, 0x28,
	0xe6, 0x5d, 0xb6, 0xfd, 0xa5, 0x13, 0xf4, 0x4e, 0x4f, 0xfe, 0xe1, 0xae, 0x55, 0x2f, 0xa6, 0xbd,
	0x64, 0xcb, 0xae, 0xdf, 0xfb, 0x5b, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x06, 0x30, 0x32, 0x10,
	0xad, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ToDoServiceClient is the client API for ToDoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ToDoServiceClient interface {
	// Create new todo task
	Create(ctx context.Context, in *domain.CreateRequest, opts ...grpc.CallOption) (*domain.CreateResponse, error)
	// Read todo task
	Read(ctx context.Context, in *domain.ReadRequest, opts ...grpc.CallOption) (*domain.ReadResponse, error)
	// Update todo task
	Update(ctx context.Context, in *domain.UpdateRequest, opts ...grpc.CallOption) (*domain.UpdateResponse, error)
	// Delete todo task
	Delete(ctx context.Context, in *domain.DeleteRequest, opts ...grpc.CallOption) (*domain.DeleteResponse, error)
	// Read all todo tasks
	ReadAll(ctx context.Context, in *domain.ReadAllRequest, opts ...grpc.CallOption) (*domain.ReadAllResponse, error)
}

type toDoServiceClient struct {
	cc *grpc.ClientConn
}

func NewToDoServiceClient(cc *grpc.ClientConn) ToDoServiceClient {
	return &toDoServiceClient{cc}
}

func (c *toDoServiceClient) Create(ctx context.Context, in *domain.CreateRequest, opts ...grpc.CallOption) (*domain.CreateResponse, error) {
	out := new(domain.CreateResponse)
	err := c.cc.Invoke(ctx, "/service.ToDoService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) Read(ctx context.Context, in *domain.ReadRequest, opts ...grpc.CallOption) (*domain.ReadResponse, error) {
	out := new(domain.ReadResponse)
	err := c.cc.Invoke(ctx, "/service.ToDoService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) Update(ctx context.Context, in *domain.UpdateRequest, opts ...grpc.CallOption) (*domain.UpdateResponse, error) {
	out := new(domain.UpdateResponse)
	err := c.cc.Invoke(ctx, "/service.ToDoService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) Delete(ctx context.Context, in *domain.DeleteRequest, opts ...grpc.CallOption) (*domain.DeleteResponse, error) {
	out := new(domain.DeleteResponse)
	err := c.cc.Invoke(ctx, "/service.ToDoService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) ReadAll(ctx context.Context, in *domain.ReadAllRequest, opts ...grpc.CallOption) (*domain.ReadAllResponse, error) {
	out := new(domain.ReadAllResponse)
	err := c.cc.Invoke(ctx, "/service.ToDoService/ReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToDoServiceServer is the server API for ToDoService service.
type ToDoServiceServer interface {
	// Create new todo task
	Create(context.Context, *domain.CreateRequest) (*domain.CreateResponse, error)
	// Read todo task
	Read(context.Context, *domain.ReadRequest) (*domain.ReadResponse, error)
	// Update todo task
	Update(context.Context, *domain.UpdateRequest) (*domain.UpdateResponse, error)
	// Delete todo task
	Delete(context.Context, *domain.DeleteRequest) (*domain.DeleteResponse, error)
	// Read all todo tasks
	ReadAll(context.Context, *domain.ReadAllRequest) (*domain.ReadAllResponse, error)
}

// UnimplementedToDoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedToDoServiceServer struct {
}

func (*UnimplementedToDoServiceServer) Create(ctx context.Context, req *domain.CreateRequest) (*domain.CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedToDoServiceServer) Read(ctx context.Context, req *domain.ReadRequest) (*domain.ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedToDoServiceServer) Update(ctx context.Context, req *domain.UpdateRequest) (*domain.UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedToDoServiceServer) Delete(ctx context.Context, req *domain.DeleteRequest) (*domain.DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedToDoServiceServer) ReadAll(ctx context.Context, req *domain.ReadAllRequest) (*domain.ReadAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAll not implemented")
}

func RegisterToDoServiceServer(s *grpc.Server, srv ToDoServiceServer) {
	s.RegisterService(&_ToDoService_serviceDesc, srv)
}

func _ToDoService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domain.CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ToDoService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).Create(ctx, req.(*domain.CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domain.ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ToDoService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).Read(ctx, req.(*domain.ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domain.UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ToDoService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).Update(ctx, req.(*domain.UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domain.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ToDoService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).Delete(ctx, req.(*domain.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domain.ReadAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ToDoService/ReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).ReadAll(ctx, req.(*domain.ReadAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ToDoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.ToDoService",
	HandlerType: (*ToDoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ToDoService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _ToDoService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ToDoService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ToDoService_Delete_Handler,
		},
		{
			MethodName: "ReadAll",
			Handler:    _ToDoService_ReadAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bitbucket-repository-management-service/dm/proto-files/service/todo-service.proto",
}
